//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InterfaceInfo
    {
        public int InterfaceInfoID { get; set; }
        public Nullable<int> InterfaceID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<long> IfInOctets { get; set; }
        public Nullable<long> IfOutOctets { get; set; }
        public Nullable<int> IfSpeed { get; set; }
        public Nullable<bool> IsUp { get; set; }
    
        public virtual tbl_Interfaces tbl_Interfaces { get; set; }
    }
}
