//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProcessInfo
    {
        public int ProcessInfoID { get; set; }
        public int ProcessID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsRunning { get; set; }
    
        public virtual tbl_Processes tbl_Processes { get; set; }
    }
}
