//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Processes
    {
        public tbl_Processes()
        {
            this.tbl_ProcessInfo = new HashSet<tbl_ProcessInfo>();
        }
    
        public int ProcessID { get; set; }
        [Required]
        public int ClientID { get; set; }
        [Required]
        public string ProcessName { get; set; }
    
        public virtual tbl_Clients tbl_Clients { get; set; }
        public virtual ICollection<tbl_ProcessInfo> tbl_ProcessInfo { get; set; }
    }
}
