//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_ClientTypes
    {
        public tbl_ClientTypes()
        {
            this.tbl_Clients = new HashSet<tbl_Clients>();
        }
    
        public int ClientTypeID { get; set; }

        [DisplayName("Type Name")]
        [Required]
        public string TypeName { get; set; }

        [DisplayName("Property List")]
        [Required]
        public string PropertyList { get; set; }

        [DisplayName("SNMP Device?")]
        [Required]
        public Nullable<bool> IsSNMPDevice { get; set; }
    
        public virtual ICollection<tbl_Clients> tbl_Clients { get; set; }
    }
}
